import image1 from '@assets/images/products/1.jpeg'

const reviewMock1 = [
  {
    author: 'John Doe',
    rate: 5,
    commentary: 'amazing',
  },
  {
    author: 'Jane Doe',
    rate: 3,
    commentary: 'nice',
  },
  {
    author: 'Joseph',
    rate: 1,
    commentary: 'Terrible',
  },
]

const reviewMock2 = [
  {
    author: 'John Doe',
    rate: 2,
    commentary: 'amazing',
  },
  {
    author: 'Joseph',
    rate: 5,
    commentary: 'Nice',
  },
]

export const products = [
  {
    id: 1,
    name: 'test 1',
    description: 'test description 1',
    price: 5,
    discount: 5,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 2,
    name: 'test 2',
    description: 'test description 2',
    price: 10,
    discount: 10,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 3,
    name: 'test 3',
    description: 'test description 3',
    price: 150,
    discount: 20,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 4,
    name: 'test 4',
    description: 'test description 4',
    price: 130,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 5,
    name: 'test 5',
    description: 'test description 5',
    price: 120,
    discount: 0,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 6,
    name: 'test 6',
    description: 'test description 6',
    price: 100,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 7,
    name: 'test 7',
    description: 'test description 7',
    price: 103,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 8,
    name: 'test 8',
    description: 'test description 8',
    price: 200,
    discount: 0,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 9,
    name: 'test 9',
    description: 'test description 9',
    price: 10,
    discount: 35,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 10,
    name: 'test 10',
    description: 'test description 10',
    price: 51,
    discount: 50,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 11,
    name: 'test 11',
    description: 'test description 11',
    price: 345,
    discount: 0,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 12,
    name: 'test 12',
    description: 'test description 12',
    price: 235,
    discount: 0,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 13,
    name: 'test 13',
    description: 'test description 13',
    price: 255,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 14,
    name: 'test 14',
    description: 'test description 14',
    price: 325,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
  {
    id: 15,
    name: 'test 15',
    description: 'test description 15',
    price: 553,
    discount: 0,
    reviews: reviewMock2,
    images: [image1, image1],
  },
  {
    id: 16,
    name: 'test 16',
    description: 'test description 16',
    price: 566,
    discount: 0,
    reviews: reviewMock1,
    images: [image1, image1],
  },
]
